services:
  users-management:
    container_name: FastAPI-users-management
    restart: unless-stopped
    build:
      context: .
      dockerfile: deploy.Dockerfile
    ports:
      - ${APP_HOST_PORT}:8000
    networks:
      - fastapi_net
    env_file:
      - .env
    mem_limit: 512m
    cpus: '1'


networks:
  fastapi_net:
    external: true
    name: FastAPI_app
    # If the network does not exist, create it:
    # docker network create FastAPI_app
